name: Trigger Digital Garden Repository Update
on: push
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: myrotvorets/trigger-repository-dispatch-action@1.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repo: oneacik/gatsby-digital-garden
          type: update-mindoo 
      - name: Beta Repository Dispatch
        uses: myrotvorets/trigger-repository-dispatch-action@1.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repo: oneacik/svelte-static-digital-garden
          type: update-mindoo
